### ISSUE TITLE
Bug: Drift Python client can not be installed on Apple M1 Device

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/DriftPythonClient#13]
### What happened?

I am unable to install Drift Python Client on Apple M1 device (ARM64). Trying to install from pip leads to `ERROR: Failed building wheel for wavelet-buffer`

### Version

latest

### OS

MacOS

### Programming Language

Python

### Snippet to repeat the bug

pip install drift-python-client

### Logs

```Shell
➜  Desktop pip install drift-python-client
Collecting drift-python-client
  Using cached drift_python_client-0.2.0-py3-none-any.whl (15 kB)
Collecting numpy==1.23.1
  Using cached numpy-1.23.1-cp39-cp39-macosx_11_0_arm64.whl (13.3 MB)
Collecting wavelet-buffer~=0.3.0
  Using cached wavelet-buffer-0.3.0.tar.gz (45 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting paho-mqtt==1.6.1
  Using cached paho-mqtt-1.6.1.tar.gz (99 kB)
  Preparing metadata (setup.py) ... done
Collecting influxdb-client==1.30.0
  Using cached influxdb_client-1.30.0-py3-none-any.whl (699 kB)
Collecting drift-protocol~=0.1.0
  Using cached drift_protocol-0.1.0-py3-none-any.whl (12 kB)
Collecting minio==7.1.10
  Using cached minio-7.1.10-py3-none-any.whl (76 kB)
Collecting deprecation==2.1.0
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: packaging in /Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/site-packages (from deprecation==2.1.0->drift-python-client) (21.3)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/site-packages (from influxdb-client==1.30.0->drift-python-client) (2.8.2)
Requirement already satisfied: urllib3>=1.26.0 in /Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/site-packages (from influxdb-client==1.30.0->drift-python-client) (1.26.7)
Requirement already satisfied: certifi>=14.05.14 in /Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/site-packages (from influxdb-client==1.30.0->drift-python-client) (2021.10.8)
Collecting rx>=3.0.1
  Using cached Rx-3.2.0-py3-none-any.whl (199 kB)
Requirement already satisfied: setuptools>=21.0.0 in /Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/site-packages (from influxdb-client==1.30.0->drift-python-client) (56.0.0)
Collecting protobuf==3.11.1
  Using cached protobuf-3.11.1-py2.py3-none-any.whl (434 kB)
Requirement already satisfied: six>=1.9 in /Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/site-packages (from protobuf==3.11.1->drift-protocol~=0.1.0->drift-python-client) (1.16.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/site-packages (from packaging->deprecation==2.1.0->drift-python-client) (2.4.7)
Using legacy 'setup.py install' for paho-mqtt, since package 'wheel' is not installed.
Building wheels for collected packages: wavelet-buffer
  Building wheel for wavelet-buffer (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for wavelet-buffer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [110 lines of output]
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 13.1.6.13160021
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is AppleClang 13.1.6.13160021
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_cmake_test_compile/build
      -- The C compiler identification is AppleClang 13.1.6.13160021
      -- The CXX compiler identification is AppleClang 13.1.6.13160021
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Run conan
      -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
      -- Conan: checking conan executable
      -- Conan: Found program /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/bin/conan
      -- Conan: Version found Conan version 1.51.1
      -- Conan executing: /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/bin/conan install . --remote conancenter --build missing --settings build_type=Release --settings compiler=apple-clang --settings compiler.version=13.1 --settings compiler.libcxx=libc++
      Configuration:
      [settings]
      arch=armv8
      arch_build=armv8
      build_type=Release
      compiler=apple-clang
      compiler.libcxx=libc++
      compiler.version=13.1
      os=Macos
      os_build=Macos
      [options]
      [build_requires]
      [env]
      
      ERROR: boost/1.73.0: Cannot load recipe.
      Error loading conanfile at '/Users/kaiser/.conan/data/boost/1.73.0/_/_/export/conanfile.py': Unable to load conanfile in /Users/kaiser/.conan/data/boost/1.73.0/_/_/export/conanfile.py
        File "/Users/kaiser/.pyenv/versions/3.9.6/lib/python3.9/imp.py", line 171, in load_source
          module = _load(spec)
        File "<frozen importlib._bootstrap>", line 711, in _load
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/Users/kaiser/.conan/data/boost/1.73.0/_/_/export/conanfile.py", line 1, in <module>
          from conan.tools.apple import is_apple_os
      ImportError: cannot import name 'is_apple_os' from 'conan.tools.apple' (/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/lib/python3.9/site-packages/conan/tools/apple/__init__.py)
      
      CMake Error at /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_skbuild/macosx-12.0-arm64-3.9/cmake-build/conan.cmake:651 (message):
        Conan install failed='1'
      Call Stack (most recent call first):
        /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/CMakeLists.txt:45 (conan_cmake_install)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeFiles/CMakeError.log".
        File "/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 637, in setup
          env = cmkr.configure(
        File "/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 328, in configure
          raise SKBuildError(
      
      
      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_skbuild/macosx-12.0-arm64-3.9/cmake-build
        Command:
          cmake /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/python -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_skbuild/macosx-12.0-arm64-3.9/cmake-install/python/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.9.6 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/Users/kaiser/.pyenv/versions/3.9.6/bin/python3 -DPython3_INCLUDE_DIR:PATH=/Users/kaiser/.pyenv/versions/3.9.6/include/python3.9 -DPython3_LIBRARY:PATH=/Users/kaiser/.pyenv/versions/3.9.6/lib/libpython3.9.a -DPython_EXECUTABLE:FILEPATH=/Users/kaiser/.pyenv/versions/3.9.6/bin/python3 -DPython_INCLUDE_DIR:PATH=/Users/kaiser/.pyenv/versions/3.9.6/include/python3.9 -DPython_LIBRARY:PATH=/Users/kaiser/.pyenv/versions/3.9.6/lib/libpython3.9.a -DPYTHON_EXECUTABLE:FILEPATH=/Users/kaiser/.pyenv/versions/3.9.6/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/Users/kaiser/.pyenv/versions/3.9.6/include/python3.9 -DPYTHON_LIBRARY:PATH=/Users/kaiser/.pyenv/versions/3.9.6/lib/libpython3.9.a -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
      
      Traceback (most recent call last):
      
      An error occurred while configuring with CMake.
        Command:
          cmake /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/python -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_skbuild/macosx-12.0-arm64-3.9/cmake-install/python/src/wavelet_buffer -DPYTHON_VERSION_STRING:STRING=3.9.6 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/Users/kaiser/.pyenv/versions/3.9.6/bin/python3 -DPython3_INCLUDE_DIR:PATH=/Users/kaiser/.pyenv/versions/3.9.6/include/python3.9 -DPython3_LIBRARY:PATH=/Users/kaiser/.pyenv/versions/3.9.6/lib/libpython3.9.a -DPython_EXECUTABLE:FILEPATH=/Users/kaiser/.pyenv/versions/3.9.6/bin/python3 -DPython_INCLUDE_DIR:PATH=/Users/kaiser/.pyenv/versions/3.9.6/include/python3.9 -DPython_LIBRARY:PATH=/Users/kaiser/.pyenv/versions/3.9.6/lib/libpython3.9.a -DPYTHON_EXECUTABLE:FILEPATH=/Users/kaiser/.pyenv/versions/3.9.6/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/Users/kaiser/.pyenv/versions/3.9.6/include/python3.9 -DPYTHON_LIBRARY:PATH=/Users/kaiser/.pyenv/versions/3.9.6/lib/libpython3.9.a -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-build-env-14zmvb9y/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
        Source directory:
          /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/python
        Working directory:
          /private/var/folders/bb/cg9xhbgd1yn2vk_vg7bp675m0000gn/T/pip-install-4x5hgl1p/wavelet-buffer_efe7be1a554c4276835e38d10a5db56f/_skbuild/macosx-12.0-arm64-3.9/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wavelet-buffer
Failed to build wavelet-buffer
ERROR: Could not build wheels for wavelet-buffer, which is required to install pyproject.toml-based projects
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
The problem is that boost conan recipe needs 1.52 conan, but wavelet user requires 1.51.1. I'll update it in Wavelet Buffer
