### ISSUE TITLE
Bug: Failed parse data: Invalid element size detected

### ISSUE THREAD

**Issue by mmaciejak** [panda-official/DriftPythonClient#22]
### What happened?

While trying to download data error happens.

Output from that snippet:

```
Starting download from 2022-11-17 11:30:00 to 2022-11-17 11:30:01 UTC
topics are: ['aufwickler-data', 'camera-1', 'cpu', 'damage-1', 'debug-camera-1', 'disk', 'kernel', 'mem', 'net', 'netstat', 'processes', 'rezeptmanager-data', 'swap', 'system', 'temp', 'trigger']
dict is: ['camera-1/1668684600200.dp', 'camera-1/1668684600402.dp', 'camera-1/1668684600603.dp', 'camera-1/1668684600805.dp']
image 0,  package: <drift_client.drift_data_package.DriftDataPackage object at 0x000001CD10E23D30> downloading
Failed parse data: Invalid element size detected
Traceback (most recent call last):
  File "E:\bbraun_onsite\bbraun_download.py", line 79, in <module>
    get_data(start_utc_time_stripped)
  File "E:\bbraun_onsite\bbraun_download.py", line 25, in get_data
    raw_img = package.as_np()
  File "E:\bbraun_onsite\.venv\lib\site-packages\drift_client\drift_data_package.py", line 16, in dec
    return func(self)
  File "E:\bbraun_onsite\.venv\lib\site-packages\drift_client\drift_data_package.py", line 120, in as_np
    return self.as_buffer().compose(scale_factor)
AttributeError: 'NoneType' object has no attribute 'compose'
```

### Version

0.2.1

### OS

Windows

### Snippet to repeat the bug

```
def get_data(start_time):
    client = DriftClient("tesa-1d4.local", os.getenv("DRIFT_PASSWORD"))
    topics = ["camera-1"]
    end_time = start_time + timedelta(seconds = 1)

    print(f'Starting download from {start_time} to {end_time} UTC')
    print(f'topics are: {client.get_topics()}')

    for topic in topics:
        packages = client.get_package_names(topic, start_time.strftime("%Y-%m-%d %H:%M:%S"), end_time.strftime("%Y-%m-%d %H:%M:%S"))
        print(f'dict is: {packages}')

        for i, package in enumerate(packages):
            package = client.get_item(str(package))
            if package.status_code == 0:
                print(f'image {i},  package: {package} downloading')
                raw_img = package.as_np()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
This is a bug in WaveletBuffer::Parse. I'll move the issue there.
